@startuml
'https://plantuml.com/class-diagram

class Sorter
enum InputTxt
enum OutputTxt
class Converters
interface ScanInputAndConvert
interface ConvertAndOutput

InputTxt --> ScanInputAndConvert
ScanInputAndConvert --> AlphabeticalSorter
AlphabeticalSorter --> ConvertAndOutput
ConvertAndOutput --> OutputTxt

Converters --* ConvertAndOutput
Converters --* ScanInputAndConvert
Sorter --* AlphabeticalSorter

class Sorter{
-AlphabeticalSorter
}

class AlphabeticalSorter

class Converters {
-ScanInputAndConvert()
-ConvertAndOutput()
}

enum InputTxt {
-names in default order
-number of names
}

enum OutputTxt {
-names alphabetically sorted
-number of names
}
@enduml