@startuml
'https://plantuml.com/class-diagram

class Input{
-convertInput
}

interface convertInput

convertInput *-- Input

class Histogram{
-wordCounter
-frequencySorter
-frequencyPrinter
}

interface wordCounter
interface frequencySorter
interface frequencyPrinter

wordCounter *-- Histogram
frequencySorter *-- Histogram
frequencyPrinter *-- Histogram

enum inputTxt{
string of repeating words
}

inputTxt --> convertInput
convertInput --> wordCounter
wordCounter --> frequencySorter
frequencySorter --> frequencyPrinter

@enduml