@startuml
'https://plantuml.com/class-diagram

class Replacer
class Convert

interface wordReplacer
interface convertInput
interface convertOutput

enum inputTxt
enum outputTxt
enum fileName

class Replacer{
-wordReplacer
}

class Convert {
-covertInput
-convertOutput
}

enum inputTxt{
-default statement
}

enum outputTxt{
-modified statement
}

inputTxt --> convertInput
convertInput --> wordReplacer
wordReplacer --> outputTxt

fileName *-- wordReplacer

wordReplacer *-- Replacer

convertOutput *-- Convert
convertInput *-- Convert


@enduml