@startuml
'https://plantuml.com/class-diagram

class InfoGetters{
-getName
-getAuthor
-getJava
-getCss
}

class Html{
-htmlMaker
}

interface getName
interface getAuthor
interface getJava
interface getCss

InfoGetters --* getName
InfoGetters --* getAuthor
InfoGetters --* getJava
InfoGetters --* getCss

Html --* htmlMaker

getName --> htmlMaker
getName ..> getAuthor
getAuthor --> htmlMaker
getAuthor ..> getJava
getJava --> htmlMaker
getJava ..> getCss
getCss --> htmlMaker

@enduml