@startuml
'https://plantuml.com/class-diagram

class Table
enum inputTxt
class Converters
interface readToArray
interface tableSpacer
interface tableMaker

inputTxt --> readToArray
readToArray --> tableMaker
tableSpacer --> tableMaker

Table --* tableSpacer
Table --* tableMaker
Converters --* readToArray

class Table{
-tableMaker
-tableSpacer
}

class Converters{
-readToArray
}


enum inputTxt {
-first name
-last name
-salary
}


@enduml